### ISSUE TITLE
Incorrect documentation or examples for `map`?

### ISSUE THREAD

**Issue by Schnouki** [Doist/ffs#50]
Hi Gonçalo,

I had a look at the [anatomy of rules](https://doist.github.io/ffs/feature-flags/anatomy-of-rules/), but I can't reconcile the documentation for `map` and the examples. Is it an error in the doc, or in my brain? 😅

To be more precise:
- example for a gradual rollout: `map(now(), datetime("2022-11-08"), datetime("2022-11-15"), 0, 1)`
- `map` syntax: `map(instart, inend, outstart, outend, value)`

That would mean that in the example, `instart`, `inend`, and `outstart` are dates, and `outend` and `value` are integers. That seems wrong...
So, either the example should be `map(datetime("2022-11-08"), datetime("2022-11-15"), 0, 1, now())`, or the syntax should be `map(value, instart, inend, outstart, outend)`.

Or am I missing something? 🤔

**Comment by Schnouki** [comment]
Looks like the [syntax is correct](https://github.com/Doist/ffs/blob/0465d2205ae87354b52041d48a31c514cb01708e/ffs-shared/rule/src/commonMain/kotlin/rule/RuleEval.kt#L427-L433), so it's probably the example that is wrong :)

**Comment by goncalossilva** [comment]
Good catch. I'll fix this if you don't send a PR in the meantime. 😄
